# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://n-sakib.github.com
title: Nazmus Sakib
email: ns.sanim@gmail.com
author: YNazmus Sakib
description: > # "I am an independent developer, blogger and student currently enrolled in CS in BRAC University."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 
